Repository OSWeekends/osw-hacktoberfest-2019, pull requests merged in 2019-10, with the labels that each got.

#24 😎 Best contributing ever
  CONTRIBUTING.md
Labels: documentation

#25 [ci skip] Best readme ever 🔄
  README.md
  src/assets/generate.png
  src/assets/main.png
Labels: documentation

#66 Add contributors location came from
  .all-contributorsrc
  .github/workflows/greetings.yml
  .github/workflows/nodejs.yml
  CONTRIBUTING.md
  README.md
  nodejs.yml
  src/assets/contributors.json
  src/views/Generate/Index.vue
  src/views/Home/Contributor.vue
  src/views/Stats/ColorWidget.vue
Labels: under-review

#72 Update contributors.json
  src/assets/contributors.json
Labels: needs-review

#80 Add asapabedi to contributors.json
  src/assets/contributors.json
Labels: needs-change

#79 Add jnat01 as contributor
  src/assets/contributors.json
Labels: needs-change

#42 Add Manrique Lopez to contributors.json
  src/assets/contributors.json
Labels: needs-change
